# Generated by Django 6.0.3 on 2026-04-09 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursesection',
            name='batch',
        ),
        migrations.AddField(
            model_name='coursesection',
            name='batches',
            field=models.ManyToManyField(related_name='course_sections', to='academics.batch'),
        ),
    ]
